version: '3'
services:
    redis:
        image: redis:alpine
    web:
        command: ["sh", "/tmp/start.sh", "django"]
        depends_on:
            - redis
        image: jonathanhs/pyroid-docker:0.1
        ports:
            - "8080:80"
